### ISSUE TITLE
Week 4 Individual Review Ticket - Derrick Huang

### ISSUE THREAD

**Issue by Pitsco** [PunarvasuS/PopcornCritics#38]
# Score: 4.5/5          Peer Reviewer: Armaan Shamsaasef
# Accounts and Logins
## [Create Task on Replit](https://replit.com/@DerrickHuang2)
- [x] CB Create Task Coding requirements documented
- [x] Runtime of Code(with comments) on Replit/Intellij
### Accounts and Logins Challenges/Hacks ( 3 Points - Team)
- Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
- Analysis: the [csp.nighthawkcodingsociety.com](http://csp.nighthawkcodingsociety.com/) implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
- [x] Hack#1 Add Phone Number to Sign Up / Authorization screen
- [x] Hack#2 Add logout to CRUD screen
- [x] Hack#3 Add login_required to another portion of the project
- [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by xXAASXx** [comment]
The code for Hack #2 is there but when running on the website it does not work and I want you to try out the extra credit as it can pay off in the future. Well done on the Create Task all it needs is more comments on the code but overall it works and does a good job doing what CB wants. 
0.5/1 for Hack #2 
College Board Create Task Score is 2/2
- more comments needed but good job
