### ISSUE TITLE
Week 4 Review Ticket

### ISSUE THREAD

**Issue by ProRichyMan** [PunarvasuS/PopcornCritics#39]
# Score 4.9/5 (Graded by Alex Do)

Link To Github Page: [Link](https://prorichyman.github.io/NathanIndividual/)

Create Task
- [x] Create Task Coding requirements documented
- [x] Runtime of Code

Accounts and Logins
- [x] Hack 1 Add Phone Number to Sign Up / Authorization screen
- [x] Hack 2 Add logout to CRUD screen
- [x] Hack 3 Add login_required to another portion of the project

Extra Credit
- [ ] A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by AlexD017** [comment]
# Score: 4.9/5 Graded by: Alex Do
Comment: Try to work on showing the runtime of the login and signup
### CB Create Task completed and documented on GH Pages 
- [x] CB Create Task Coding requirements documented
- [x] Runtime of Code(with comments) on Replit/Intellij

### Accounts and Logins Challenges/Hacks

- [x] Hack#1 Add Phone Number to Sign Up / Authorization screen
- [x] Hack#2 Add logout to CRUD screen
- [x] Hack#3 Add login_required to another portion of the project
- [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.
